name: Simple CICD for Xapo

on:
  push:
    branches: [ main ]
  pull_request:

env:
  IMAGE_NAME: bitcoin
  IMAGE_VERSION: 0.21.0

jobs:
  build-test-and-push-docker-image:
    name: Build Docker image, test security with Grype, and push it to DockerHub
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build local container
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.WORKDIR }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          push: false
          load: true

      - name: Scan image with Grype
        uses: anchore/scan-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          fail-build: true
          severity-cutoff: medium

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

  plan-test-and-apply-terraform:
    needs: build-test-and-push-docker-image
    name: Terraform fmt, init, validate, plan, and apply
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./terraform
      TF_VERSION: 1.0.0
      AWS_REGION: ap-southeast-2
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var="DockerImage=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}"
        continue-on-error: false

##    - name: Terraform apply
##      id: apply
##      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
##      run: terraform apply -auto-approve -var="DockerImage=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}"